[tool.poetry]
name = "pytss"
version = "0.1.0"
description = ""
authors = ["TonyLin <chiacheng.lin0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
